package model

import (
	"time"

	"github.com/google/uuid"
)

// AgentPlan represents a high-level financial plan generated by the AI agent
type AgentPlan struct {
	ID             uuid.UUID              `json:"id"`
	UserID         uuid.UUID              `json:"user_id"`
	Title          string                 `json:"title"`
	Description    *string                `json:"description,omitempty"`
	GoalType       string                 `json:"goal_type"` // savings, debt_payoff, budget_optimization, investment, emergency_fund, custom
	Status         string                 `json:"status"`    // draft, active, paused, completed, cancelled
	Priority       string                 `json:"priority"`  // low, medium, high, urgent
	TargetAmount   *float64               `json:"target_amount,omitempty"`
	TargetCurrency *string                `json:"target_currency,omitempty"`
	TargetDate     *time.Time             `json:"target_date,omitempty"`
	AIReasoning    *string                `json:"ai_reasoning,omitempty"`
	Metadata       map[string]interface{} `json:"metadata,omitempty"`
	CreatedAt      time.Time              `json:"created_at"`
	UpdatedAt      time.Time              `json:"updated_at"`
	CompletedAt    *time.Time             `json:"completed_at,omitempty"`

	// Populated when fetching with steps
	Steps []*PlanStep `json:"steps,omitempty"`
}

// PlanStep represents an individual action step within a plan
type PlanStep struct {
	ID               uuid.UUID              `json:"id"`
	PlanID           uuid.UUID              `json:"plan_id"`
	StepOrder        int                    `json:"step_order"`
	Title            string                 `json:"title"`
	Description      *string                `json:"description,omitempty"`
	ActionType       string                 `json:"action_type"` // transfer, goal_contribution, budget_adjustment, recurring_update, subscription_cancel, debt_payment, alert, recommendation, custom
	ActionParams     map[string]interface{} `json:"action_params"`
	Status           string                 `json:"status"` // pending, approved, executing, completed, failed, skipped
	RequiresApproval bool                   `json:"requires_approval"`
	EstimatedImpact  *float64               `json:"estimated_impact,omitempty"`
	ActualImpact     *float64               `json:"actual_impact,omitempty"`
	ScheduledAt      *time.Time             `json:"scheduled_at,omitempty"`
	ExecutedAt       *time.Time             `json:"executed_at,omitempty"`
	ErrorMessage     *string                `json:"error_message,omitempty"`
	Metadata         map[string]interface{} `json:"metadata,omitempty"`
	CreatedAt        time.Time              `json:"created_at"`
	UpdatedAt        time.Time              `json:"updated_at"`
}

// ActionApproval tracks user approval for an action step
type ActionApproval struct {
	ID              uuid.UUID              `json:"id"`
	StepID          uuid.UUID              `json:"step_id"`
	UserID          uuid.UUID              `json:"user_id"`
	ApprovalStatus  string                 `json:"approval_status"`           // pending, approved, rejected, auto_approved, expired
	ApprovalMethod  *string                `json:"approval_method,omitempty"` // manual, biometric, auto, voice
	ApprovedAt      *time.Time             `json:"approved_at,omitempty"`
	ExpiresAt       time.Time              `json:"expires_at"`
	RejectionReason *string                `json:"rejection_reason,omitempty"`
	DeviceInfo      map[string]interface{} `json:"device_info,omitempty"`
	CreatedAt       time.Time              `json:"created_at"`

	// Additional context (populated when fetching with joins)
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// ActionLog is an audit trail entry for agent actions
type ActionLog struct {
	ID                uuid.UUID              `json:"id"`
	UserID            uuid.UUID              `json:"user_id"`
	PlanID            *uuid.UUID             `json:"plan_id,omitempty"`
	StepID            *uuid.UUID             `json:"step_id,omitempty"`
	ActionType        string                 `json:"action_type"`
	ActionDescription string                 `json:"action_description"`
	Status            string                 `json:"status"` // initiated, in_progress, completed, failed, rolled_back
	RequestPayload    map[string]interface{} `json:"request_payload,omitempty"`
	ResponsePayload   map[string]interface{} `json:"response_payload,omitempty"`
	ErrorDetails      map[string]interface{} `json:"error_details,omitempty"`
	ExecutionTimeMS   *int                   `json:"execution_time_ms,omitempty"`
	IPAddress         *string                `json:"ip_address,omitempty"`
	UserAgent         *string                `json:"user_agent,omitempty"`
	CreatedAt         time.Time              `json:"created_at"`
}

// AgentConfig stores user preferences for the autonomous agent
type AgentConfig struct {
	UserID                  uuid.UUID              `json:"user_id"`
	Enabled                 bool                   `json:"enabled"`
	AutoApproveThreshold    float64                `json:"auto_approve_threshold"`
	AutoApproveCurrency     string                 `json:"auto_approve_currency"`
	RequireBiometricAbove   float64                `json:"require_biometric_above"`
	DailyAutopilotEnabled   bool                   `json:"daily_autopilot_enabled"`
	AutopilotTime           string                 `json:"autopilot_time"` // HH:MM:SS format
	AutopilotTimezone       string                 `json:"autopilot_timezone"`
	AllowedActionTypes      []string               `json:"allowed_action_types"`
	NotificationPreferences map[string]interface{} `json:"notification_preferences"`
	CreatedAt               time.Time              `json:"created_at"`
	UpdatedAt               time.Time              `json:"updated_at"`
}

// DailyAutopilotResult stores the results of daily financial analysis
type DailyAutopilotResult struct {
	ID                   uuid.UUID              `json:"id"`
	UserID               uuid.UUID              `json:"user_id"`
	RunDate              time.Time              `json:"run_date"`
	Status               string                 `json:"status"` // pending, running, completed, failed
	UpcomingBills        []interface{}          `json:"upcoming_bills,omitempty"`
	BalancePredictions   map[string]interface{} `json:"balance_predictions,omitempty"`
	GoalOpportunities    []interface{}          `json:"goal_opportunities,omitempty"`
	SubscriptionInsights []interface{}          `json:"subscription_insights,omitempty"`
	AnomaliesDetected    []interface{}          `json:"anomalies_detected,omitempty"`
	ProposedActions      int                    `json:"proposed_actions"`
	AutoApprovedActions  int                    `json:"auto_approved_actions"`
	PendingApprovals     int                    `json:"pending_approvals"`
	AnalysisDurationMS   *int                   `json:"analysis_duration_ms,omitempty"`
	ErrorMessage         *string                `json:"error_message,omitempty"`
	CreatedAt            time.Time              `json:"created_at"`
	CompletedAt          *time.Time             `json:"completed_at,omitempty"`
}

// ============================================
// Constants for validation
// ============================================

// Valid plan statuses
var ValidPlanStatuses = []string{"draft", "active", "paused", "completed", "cancelled"}

// Valid plan priorities
var ValidPlanPriorities = []string{"low", "medium", "high", "urgent"}

// Valid goal types
var ValidGoalTypes = []string{"savings", "debt_payoff", "budget_optimization", "investment", "emergency_fund", "custom"}

// Valid action types
var ValidActionTypes = []string{
	"transfer",
	"goal_contribution",
	"budget_adjustment",
	"recurring_update",
	"subscription_cancel",
	"debt_payment",
	"alert",
	"recommendation",
	"custom",
}

// Valid step statuses
var ValidStepStatuses = []string{"pending", "approved", "executing", "completed", "failed", "skipped"}

// Valid approval statuses
var ValidApprovalStatuses = []string{"pending", "approved", "rejected", "auto_approved", "expired"}

// Valid approval methods
var ValidApprovalMethods = []string{"manual", "biometric", "auto", "voice"}

// ============================================
// Request/Response types for API
// ============================================

// CreatePlanRequest is the request body for creating a plan
type CreatePlanRequest struct {
	Title          string                 `json:"title" validate:"required,min=1,max=255"`
	Description    *string                `json:"description,omitempty"`
	GoalType       string                 `json:"goal_type" validate:"required,oneof=savings debt_payoff budget_optimization investment emergency_fund custom"`
	Priority       string                 `json:"priority,omitempty"`
	TargetAmount   *float64               `json:"target_amount,omitempty"`
	TargetCurrency *string                `json:"target_currency,omitempty"`
	TargetDate     *time.Time             `json:"target_date,omitempty"`
	Metadata       map[string]interface{} `json:"metadata,omitempty"`
}

// UpdatePlanRequest is the request body for updating a plan
type UpdatePlanRequest struct {
	Title          *string                `json:"title,omitempty"`
	Description    *string                `json:"description,omitempty"`
	Priority       *string                `json:"priority,omitempty"`
	TargetAmount   *float64               `json:"target_amount,omitempty"`
	TargetCurrency *string                `json:"target_currency,omitempty"`
	TargetDate     *time.Time             `json:"target_date,omitempty"`
	Metadata       map[string]interface{} `json:"metadata,omitempty"`
}

// ApproveActionRequest is the request body for approving an action
type ApproveActionRequest struct {
	Method     string                 `json:"method,omitempty"` // manual, biometric, voice
	DeviceInfo map[string]interface{} `json:"device_info,omitempty"`
}

// RejectActionRequest is the request body for rejecting an action
type RejectActionRequest struct {
	Reason string `json:"reason,omitempty"`
}

// UpdateConfigRequest is the request body for updating agent config
type UpdateConfigRequest struct {
	Enabled                 *bool                  `json:"enabled,omitempty"`
	AutoApproveThreshold    *float64               `json:"auto_approve_threshold,omitempty"`
	AutoApproveCurrency     *string                `json:"auto_approve_currency,omitempty"`
	RequireBiometricAbove   *float64               `json:"require_biometric_above,omitempty"`
	DailyAutopilotEnabled   *bool                  `json:"daily_autopilot_enabled,omitempty"`
	AutopilotTime           *string                `json:"autopilot_time,omitempty"`
	AutopilotTimezone       *string                `json:"autopilot_timezone,omitempty"`
	AllowedActionTypes      []string               `json:"allowed_action_types,omitempty"`
	NotificationPreferences map[string]interface{} `json:"notification_preferences,omitempty"`
}

// PlanSummary is a lightweight plan representation for lists
type PlanSummary struct {
	ID             uuid.UUID  `json:"id"`
	Title          string     `json:"title"`
	GoalType       string     `json:"goal_type"`
	Status         string     `json:"status"`
	Priority       string     `json:"priority"`
	TargetAmount   *float64   `json:"target_amount,omitempty"`
	TargetCurrency *string    `json:"target_currency,omitempty"`
	TargetDate     *time.Time `json:"target_date,omitempty"`
	StepsTotal     int        `json:"steps_total"`
	StepsCompleted int        `json:"steps_completed"`
	StepsPending   int        `json:"steps_pending"`
	CreatedAt      time.Time  `json:"created_at"`
}

// PendingApprovalSummary is the response for pending approvals list
type PendingApprovalSummary struct {
	ID              uuid.UUID `json:"id"`
	PlanTitle       string    `json:"plan_title"`
	StepTitle       string    `json:"step_title"`
	ActionType      string    `json:"action_type"`
	EstimatedImpact *float64  `json:"estimated_impact,omitempty"`
	ExpiresAt       time.Time `json:"expires_at"`
	CreatedAt       time.Time `json:"created_at"`
}

// DailyBriefing is the response for the daily autopilot summary
type DailyBriefing struct {
	Date              time.Time               `json:"date"`
	Status            string                  `json:"status"`
	UpcomingBills     []UpcomingBill          `json:"upcoming_bills"`
	BalanceHealth     BalanceHealth           `json:"balance_health"`
	GoalOpportunities []GoalOpportunity       `json:"goal_opportunities"`
	PendingApprovals  int                     `json:"pending_approvals"`
	Insights          []string                `json:"insights"`
	RecommendedAction *AgentRecommendedAction `json:"recommended_action,omitempty"`
}

// UpcomingBill represents an upcoming recurring transaction
type UpcomingBill struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Amount    float64   `json:"amount"`
	Currency  string    `json:"currency"`
	DueDate   time.Time `json:"due_date"`
	DaysUntil int       `json:"days_until"`
	CanAfford bool      `json:"can_afford"`
}

// BalanceHealth represents the health of user's balances
type BalanceHealth struct {
	Status           string   `json:"status"` // healthy, warning, critical
	ProjectedBalance float64  `json:"projected_balance"`
	Currency         string   `json:"currency"`
	DaysUntilLow     *int     `json:"days_until_low,omitempty"`
	Recommendations  []string `json:"recommendations,omitempty"`
}

// GoalOpportunity represents a goal contribution opportunity
type GoalOpportunity struct {
	GoalID           uuid.UUID `json:"goal_id"`
	GoalTitle        string    `json:"goal_title"`
	CurrentProgress  float64   `json:"current_progress"`
	SuggestedAmount  float64   `json:"suggested_amount"`
	Currency         string    `json:"currency"`
	ImpactOnTimeline string    `json:"impact_on_timeline"` // "reach 2 weeks earlier"
}

// AgentRecommendedAction is the top priority action suggested by the agent (distinct from CoAI's RecommendedAction)
type AgentRecommendedAction struct {
	Type        string  `json:"type"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Impact      float64 `json:"impact"`
	Currency    string  `json:"currency"`
	Urgency     string  `json:"urgency"` // low, medium, high
}

// AutopilotStatus is the consolidated response for GET /agent/autopilot/status.
// Covers both config state and live scheduling data so the UI can render the
// AutopilotCard header ("last scan X ago · next scan at Y") in one call.
type AutopilotStatus struct {
	Enabled               bool       `json:"enabled"`
	DailyAutopilotEnabled bool       `json:"daily_autopilot_enabled"`
	AutopilotTime         string     `json:"autopilot_time,omitempty"`
	AutopilotTimezone     string     `json:"autopilot_timezone,omitempty"`
	LastRunAt             *time.Time `json:"last_run_at,omitempty"`
	NextRunEstimate       *time.Time `json:"next_run_estimate,omitempty"`
	PendingPlanCount      int        `json:"pending_plan_count"`
	PendingApprovalCount  int        `json:"pending_approval_count"`
}
