-- Migration: 0021 - Autonomous Agent Tables
-- Description: Tables for autonomous AI financial agent
-- Phase 2A: Planning engine, action execution, and approval system

-- Agent Plans: High-level financial plans generated by AI
CREATE TABLE IF NOT EXISTS agent_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    goal_type VARCHAR(50) NOT NULL, -- 'savings', 'debt_payoff', 'budget_optimization', 'investment', 'custom'
    status VARCHAR(20) NOT NULL DEFAULT 'draft', -- 'draft', 'active', 'paused', 'completed', 'cancelled'
    priority VARCHAR(10) DEFAULT 'medium', -- 'low', 'medium', 'high', 'urgent'
    target_amount DECIMAL(20, 8),
    target_currency VARCHAR(3),
    target_date TIMESTAMP WITH TIME ZONE,
    ai_reasoning TEXT, -- Why AI generated this plan
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT valid_status CHECK (status IN ('draft', 'active', 'paused', 'completed', 'cancelled')),
    CONSTRAINT valid_priority CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    CONSTRAINT valid_goal_type CHECK (goal_type IN ('savings', 'debt_payoff', 'budget_optimization', 'investment', 'emergency_fund', 'custom'))
);

CREATE INDEX idx_agent_plans_user_id ON agent_plans(user_id);
CREATE INDEX idx_agent_plans_status ON agent_plans(status);
CREATE INDEX idx_agent_plans_user_status ON agent_plans(user_id, status);

-- Plan Steps: Individual steps within a plan
CREATE TABLE IF NOT EXISTS plan_steps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_id UUID NOT NULL REFERENCES agent_plans(id) ON DELETE CASCADE,
    step_order INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    action_type VARCHAR(50) NOT NULL, -- Action type to execute
    action_params JSONB NOT NULL DEFAULT '{}', -- Parameters for the action
    status VARCHAR(20) NOT NULL DEFAULT 'pending', -- 'pending', 'approved', 'executing', 'completed', 'failed', 'skipped'
    requires_approval BOOLEAN DEFAULT true,
    estimated_impact DECIMAL(20, 8), -- Estimated financial impact
    actual_impact DECIMAL(20, 8), -- Actual impact after execution
    scheduled_at TIMESTAMP WITH TIME ZONE, -- When to execute (null = ASAP)
    executed_at TIMESTAMP WITH TIME ZONE,
    error_message TEXT,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT valid_step_status CHECK (status IN ('pending', 'approved', 'executing', 'completed', 'failed', 'skipped')),
    CONSTRAINT valid_action_type CHECK (action_type IN (
        'transfer', 'goal_contribution', 'budget_adjustment', 
        'recurring_update', 'subscription_cancel', 'debt_payment',
        'alert', 'recommendation', 'custom'
    ))
);

CREATE INDEX idx_plan_steps_plan_id ON plan_steps(plan_id);
CREATE INDEX idx_plan_steps_status ON plan_steps(status);
CREATE INDEX idx_plan_steps_scheduled ON plan_steps(scheduled_at) WHERE scheduled_at IS NOT NULL;

-- Action Approvals: Track user approvals for agent actions
CREATE TABLE IF NOT EXISTS action_approvals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    step_id UUID NOT NULL REFERENCES plan_steps(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    approval_status VARCHAR(20) NOT NULL DEFAULT 'pending', -- 'pending', 'approved', 'rejected', 'auto_approved', 'expired'
    approval_method VARCHAR(30), -- 'manual', 'biometric', 'auto', 'voice'
    approved_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() + INTERVAL '48 hours',
    rejection_reason TEXT,
    device_info JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT valid_approval_status CHECK (approval_status IN ('pending', 'approved', 'rejected', 'auto_approved', 'expired'))
);

CREATE INDEX idx_action_approvals_step_id ON action_approvals(step_id);
CREATE INDEX idx_action_approvals_user_pending ON action_approvals(user_id, approval_status) WHERE approval_status = 'pending';
CREATE INDEX idx_action_approvals_expires ON action_approvals(expires_at) WHERE approval_status = 'pending';

-- Action Logs: Comprehensive audit trail
CREATE TABLE IF NOT EXISTS action_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id UUID REFERENCES agent_plans(id) ON DELETE SET NULL,
    step_id UUID REFERENCES plan_steps(id) ON DELETE SET NULL,
    action_type VARCHAR(50) NOT NULL,
    action_description TEXT NOT NULL,
    status VARCHAR(20) NOT NULL, -- 'initiated', 'in_progress', 'completed', 'failed', 'rolled_back'
    request_payload JSONB,
    response_payload JSONB,
    error_details JSONB,
    execution_time_ms INT,
    ip_address INET,
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT valid_log_status CHECK (status IN ('initiated', 'in_progress', 'completed', 'failed', 'rolled_back'))
);

CREATE INDEX idx_action_logs_user_id ON action_logs(user_id);
CREATE INDEX idx_action_logs_plan_id ON action_logs(plan_id);
CREATE INDEX idx_action_logs_created ON action_logs(created_at DESC);
CREATE INDEX idx_action_logs_user_created ON action_logs(user_id, created_at DESC);

-- Agent Configuration: User preferences for autonomous agent
CREATE TABLE IF NOT EXISTS agent_config (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    enabled BOOLEAN DEFAULT true,
    auto_approve_threshold DECIMAL(20, 8) DEFAULT 10.00, -- Auto-approve actions under this amount
    auto_approve_currency VARCHAR(3) DEFAULT 'USD',
    require_biometric_above DECIMAL(20, 8) DEFAULT 100.00, -- Require biometric for high-value actions
    daily_autopilot_enabled BOOLEAN DEFAULT true,
    autopilot_time TIME DEFAULT '08:00:00', -- Preferred time for daily briefing
    autopilot_timezone VARCHAR(50) DEFAULT 'UTC',
    allowed_action_types TEXT[] DEFAULT ARRAY['alert', 'recommendation'], -- What agent can do automatically
    notification_preferences JSONB DEFAULT '{"push": true, "email": false}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Daily Autopilot Results: Store daily analysis results
CREATE TABLE IF NOT EXISTS daily_autopilot_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    run_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending', -- 'pending', 'running', 'completed', 'failed'
    
    -- Analysis results
    upcoming_bills JSONB DEFAULT '[]',
    balance_predictions JSONB DEFAULT '{}',
    goal_opportunities JSONB DEFAULT '[]',
    subscription_insights JSONB DEFAULT '[]',
    anomalies_detected JSONB DEFAULT '[]',
    
    -- Generated actions
    proposed_actions INT DEFAULT 0,
    auto_approved_actions INT DEFAULT 0,
    pending_approvals INT DEFAULT 0,
    
    -- Execution metrics
    analysis_duration_ms INT,
    error_message TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT unique_user_date UNIQUE (user_id, run_date),
    CONSTRAINT valid_autopilot_status CHECK (status IN ('pending', 'running', 'completed', 'failed'))
);

CREATE INDEX idx_daily_autopilot_user_date ON daily_autopilot_results(user_id, run_date DESC);
CREATE INDEX idx_daily_autopilot_status ON daily_autopilot_results(status);

-- Trigger to update updated_at timestamps
CREATE OR REPLACE FUNCTION update_agent_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_agent_plans_updated
    BEFORE UPDATE ON agent_plans
    FOR EACH ROW
    EXECUTE FUNCTION update_agent_updated_at();

CREATE TRIGGER trigger_plan_steps_updated
    BEFORE UPDATE ON plan_steps
    FOR EACH ROW
    EXECUTE FUNCTION update_agent_updated_at();

CREATE TRIGGER trigger_agent_config_updated
    BEFORE UPDATE ON agent_config
    FOR EACH ROW
    EXECUTE FUNCTION update_agent_updated_at();
