# Icon size migration script
import re, os

SIZE_MAP = {12:'xs',14:'sm',15:'sm',16:'sm',18:'md',20:'md',22:'default',24:'default',28:'lg',32:'lg',48:'xl'}

SKIP_SIZES = {10, 40}
APP_ROOT = '/Users/rezazeraat/dev/cofinance/app'

LUCIDE_ICONS = {
    'ArrowDown',
    'ArrowDownUp',
    'ArrowLeft',
    'ArrowLeftRight',
    'ArrowRight',
    'ArrowUp',
    'Award',
    'AlertCircle',
    'AlertTriangle',
    'Baby',
    'Banknote',
    'BarChart3',
    'Bell',
    'Bot',
    'BookOpen',
    'Bus',
    'Calendar',
    'CalendarDays',
    'CalendarRange',
    'Car',
    'Check',
    'CheckCircle',
    'CheckCircle2',
    'ChevronDown',
    'ChevronLeft',
    'ChevronRight',
    'ChevronUp',
    'Clock',
    'Coffee',
    'CreditCard',
    'Dog',
    'DollarSign',
    'Download',
    'Dumbbell',
    'Eye',
    'EyeOff',
    'Film',
    'Fingerprint',
    'Flame',
    'Gamepad2',
    'Gift',
    'Globe',
    'GraduationCap',
    'HandCoins',
    'Heart',
    'History',
    'Home',
    'Info',
    'Landmark',
    'LayoutDashboard',
    'Lightbulb',
    'Lock',
    'LogOut',
    'Mail',
    'Menu',
    'MessageCircle',
    'Minus',
    'Moon',
    'MoreHorizontal',
    'Music',
    'Package',
    'Pause',
    'Pencil',
    'PieChart',
    'PiggyBank',
    'Pill',
    'Pizza',
    'Play',
    'Plus',
    'Receipt',
    'RefreshCw',
    'Repeat',
    'Search',
    'Send',
    'Shirt',
    'Smartphone',
    'Sparkles',
    'Star',
    'StickyNote',
    'Sun',
    'Target',
    'Trash2',
    'TrendingDown',
    'TrendingUp',
    'Trophy',
    'User',
    'Utensils',
    'Wallet',
    'Wifi',
    'Wrench',
    'X',
    'XCircle',
    'Zap',
    'GoogleIcon',
    'LinkedInIcon',
    'GoalIcon',
    'FrequencyIcon',
    'StyledCategoryIcon',
    'CategoryIcon',
    'FeatureIcon',
    'Icon',
    'StatusIcon',
}

FILES = [
    'app/(app)/(tabs)/index.tsx',
    'app/(app)/(tabs)/add.tsx',
    'app/(app)/(tabs)/goals.tsx',
    'app/(app)/(tabs)/reports.tsx',
    'app/(app)/(tabs)/wallet/index.tsx',
    'app/(app)/(tabs)/wallet/history.tsx',
    'app/(app)/(tabs)/wallet/convert.tsx',
    'app/(app)/(tabs)/wallet/chat.tsx',
    'app/(app)/(tabs)/wallet/ai.tsx',
    'app/(app)/(tabs)/_layout.tsx',
    'app/(app)/profile.tsx',
    'app/(app)/budgets.tsx',
    'app/(app)/recurring.tsx',
    'app/(app)/subscriptions.tsx',
    'app/(app)/challenges.tsx',
    'app/(app)/badges.tsx',
    'app/(app)/loans.tsx',
    'app/(app)/notes.tsx',
    'app/(app)/onboarding.tsx',
    'app/(app)/change-password.tsx',
    'app/(app)/notification-settings.tsx',
    'app/(app)/historical.tsx',
    'app/(auth)/login.tsx',
    'app/(auth)/register.tsx',
    'app/(auth)/forgot-password.tsx',
    'app/(auth)/reset-password.tsx',
    'app/(public)/index.tsx',
    'app/(public)/about.tsx',
    'app/(public)/converter.tsx',
    'src/components/ui/BottomSheet.tsx',
    'src/components/ui/EmptyState.tsx',
    'src/components/ui/CollapsibleSection.tsx',
    'src/components/ui/SwipeableRow.tsx',
    'src/components/ui/Select.tsx',
    'src/components/ui/CurrencyPicker.tsx',
    'src/components/features/CurrencyConverter.tsx',
    'src/components/features/Notes/NoteFormModal.tsx',
    'src/components/features/Reports/MonthlyReportView.tsx',
    'src/components/features/HealthScore/HealthScoreCard.tsx',
    'src/components/features/WeeklyRecap/WeeklyRecapCard.tsx',
    'src/components/features/DailyTip/DailyTipCard.tsx',
]

def get_rel_import(fp):
    fd = os.path.dirname(os.path.join(APP_ROOT, fp))
    ip = os.path.join(APP_ROOT, "src", "constants", "icons")
    r = os.path.relpath(ip, fd)
    if not r.startswith("."): r = "./" + r
    return r

